# Generated by Django 5.1.7 on 2025-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Número de telefono')),
                ('password', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿El usuario esta activo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Autorizado para ser staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='¿Es administrador?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Users',
            },
        ),
    ]
