# Generated by Django 5.1.7 on 2025-03-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='cd57b819927de31b7f5e86df8815b1e0', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
