# Generated by Django 5.1.7 on 2025-03-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='05317727947e4891d143b5ff0239d08e', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
