# Generated by Django 5.1.7 on 2025-03-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default='74a4528698e7fd3f133686ba0435257a', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
